version: '3.4'

services:


  userdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: src/Services/Users/Users.API/Dockerfile
